<a href="https://colab.research.google.com/github/Felicette1963/Python_Numpy_Colab/blob/main/20230619_Python_Numpy_Basic_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Hell world")

Hell world


In [3]:
import numpy as np

# Numpy 기초


# 배열(Array)

*   많은 데이터를 하나의 변수에 넣는 법? : 리스트
*   하지만 리스트는...

  *   속도가 느리다
  *   메모리를 많이 차지한다

> 그래서? 배열(Array)을 사용한다

적은 메모리로 많은 데이터를 빠르게 처리할 수 있음

## 특징
1. 모든 원소가 같은 **자료형**이어야 함
2. 원소의 갯수를 바꿀 수 없음

> 그런데 파이썬은 자체적으로 배열 자료형을 제공하지 않음<br>
> 그래서 우리는 **넘파이(Numpy)** 패키지를 import해서 사용

## 1차원 배열
* 리스트나 튜플처럼 한 줄로 이루어진 형태의 배열

## ndarray
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

In [6]:
import random

def averge_python(n):
  s = 0;
  for i in range(n):
    s += random.random()
  return s / n

In [15]:
%time averge_python(100_000_000)
# CPU times: user 11.7 s, sys: 0 ns, total: 11.7 s
# Wall time: 11.8 s

CPU times: user 11.7 s, sys: 0 ns, total: 11.7 s
Wall time: 11.8 s


0.4999977317440715

In [11]:
import random

def averge_np_python(n):
  s = 0;
  s = np.random.random(n)
  return s.mean()

In [16]:
%time averge_np_python(100_000_000)
# CPU times: user 993 ms, sys: 179 ms, total: 1.17 s
# Wall time: 1.18 s
# numpy를 쓰는 이유 일반적인 리스트에 비해 속도가 빠른 계산을 한다.

CPU times: user 993 ms, sys: 179 ms, total: 1.17 s
Wall time: 1.18 s


0.4999764657635501

## 벡터화 연산
* 배열 객체는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리**하는 벡터화 연산(vectorized operation)을 지원

In [23]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
data * 2
# 리스트의 곱셈은 객체의 갯수가 곱셈이 된다.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
%%time
# %%time은 해당 전체 코드의 실행 시간을 기록
answer = []
for d in data:
  answer = d *2
answer

CPU times: user 21 µs, sys: 1 µs, total: 22 µs
Wall time: 27.2 µs


18

In [26]:
%%timeit
# %%timeit은 해당 전체 코드의 일정 단위 까지 반복 실행간 기록을 남긴다.
answer = []
for d in data:
  answer = d *2
answer
# 387 ns ± 6.86 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

387 ns ± 6.86 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [27]:
%%time
# 리스트 컴플레이션 방식
answer = [d * 2 for d in data]
answer

CPU times: user 23 µs, sys: 0 ns, total: 23 µs
Wall time: 26.7 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [28]:
%%timeit
# 리스트 컴플레이션 방식
answer = [d * 2 for d in data]
answer

801 ns ± 253 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [30]:
# 백터화 연산
arr = np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
%time arr * 2
# 벡터화 연산 방법

CPU times: user 54 µs, sys: 3 µs, total: 57 µs
Wall time: 61 µs


array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72])

In [36]:
%timeit arr * 2

1.32 µs ± 406 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [39]:
a = np.array(range(1,4))
b = np.array(range(10,40, 10))
c = a * 10
print(a)
print(b)
print(c)

[1 2 3]
[10 20 30]
[10 20 30]


In [40]:
a * b + 2

array([12, 42, 92])

In [41]:
a ** 2, b ** 0.05

(array([1, 4, 9]), array([1.12201845, 1.16158635, 1.18537582]))

In [43]:
print(a == 2)
print(b > 10)

[False  True False]
[False  True  True]


In [44]:
# & : and
'''
(array([False,  True, False]),
 array([False,  True,  True])
'''
(a == 2) & (b > 10), (a == 2) | (b > 10)
# 논리 연산

(array([False,  True, False]), array([False,  True,  True]))

## 2차원 배열
* `ndarray`는 N-dimensional Array의 약자, 즉 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원
* 2차원 배열 = 행렬 (matrix)
* 가로줄 : 행(row), 세로줄 : 열(column)
> 엑셀 스프레드시트와 같은 형태의 배열

* 리스트의 리스트(list of list)를 이용하여 2차원 배열 생성
    * 안쪽 리스트의 길이 : 행렬의 열의 수 (가로 크기)
    * 바깥쪽 리스트의 길이 : 행렬의 행의 수 (세로 크기)

In [46]:
arr_2d = np.array([[0,1,2], [3,4,5]])
arr_2d

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
# 행의 갯수, 열의 갯수
len(arr_2d), len(arr_2d[0]), len(arr_2d[1])

(2, 3, 3)

In [49]:
# 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시
# m : matrix (2차원 배열, 행렬)
# t : three-dimention
t = np.array(
    [
        [
            [1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12],
        ],
        [
            [11, 12, 13, 14],
            [15, 16, 17, 18],
            [19, 20, 21, 22],  # 4개
        ],  # 3개
    ]  # 가장 밖 리스트 -> 요소 2개
)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [50]:
# 깊이, 행, 열
len(t), len(t[0]), len(t[0][0])

(2, 3, 4)

## 배열의 차원과 크기 알아내기
* `ndim`, `shape` **속성** 사용
> 속성 : 괄호 없이 이름만 써서 값을 호출

* `ndim` : 배열의 차원
* `shape` : 배열의 크기

In [ ]:
a = np.array(range(1, 4))
a

array([1, 2, 3])

In [ ]:
a.ndim, a.shape

(1, (3,))

In [ ]:
m = np.array((range(3), range(3, 6)))  # 3개 3개.
m

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
m.ndim, m.shape

(2, (2, 3))

In [ ]:
t.ndim, t.shape

(3, (2, 3, 4))

## 배열의 복사
* copy와 view의 차이점은 copy는 새 배열(깊은 복사)이고 view는 원래 배열과 연결 되어 있다는 것(얕은 복사)
* copy는 데이터를 소유하며 copy에 대한 변경 사항은 원본 배열에 영향을 미치지 않으며 원본 배열에 대한 변경은 copy에 영향을 주지 않음
* view는 데이터를 소유하지 않으며 view에 대한 모든 변경 사항은 원래 배열에 영향을 미치고 원래 배열에 대한 모든 변경 사항은 보기에 영향을 줌

In [53]:
arr = np.array(range(1, 6))
arr2 = arr  # 복사 -> 할당/대입
arr[0] = 40
arr, arr2

(array([40,  2,  3,  4,  5]), array([40,  2,  3,  4,  5]))

In [54]:
arr = np.array(range(1, 6))
arr2 = arr.view()  # 읽기 전용의 사본 (일부러 원본과 연결된 사본)
arr[0] = 40
arr, arr2

(array([40,  2,  3,  4,  5]), array([40,  2,  3,  4,  5]))

In [55]:
arr = np.array(range(1, 6))
arr2 = arr.copy()  # 얕은 복사 x <- 깊은 복사.
arr[0] = 40
arr, arr2

(array([40,  2,  3,  4,  5]), array([1, 2, 3, 4, 5]))

In [56]:
arr3 = np.array([arr, arr])  # np.array로 만들어지면서 완전하 사본
arr4 = arr3.copy()
arr3, arr4

(array([[40,  2,  3,  4,  5],
        [40,  2,  3,  4,  5]]),
 array([[40,  2,  3,  4,  5],
        [40,  2,  3,  4,  5]]))

In [57]:
arr[0] = 41
arr4[0] = 43
arr3, arr4

(array([[40,  2,  3,  4,  5],
        [40,  2,  3,  4,  5]]),
 array([[43, 43, 43, 43, 43],
        [40,  2,  3,  4,  5]]))

## 배열의 인덱싱

### 일차원 배열
* 리스트의 인덱싱과 같음

In [58]:
a = np.array(range(5))
print(a)  # 1차원 배열
print(a[0], a[2], a[-1], a[len(a)-1])

[0 1 2 3 4]
0 2 4 4


### 다차원 배열
* 콤마(comma, `,`)를 사용하여 접근
* 콤마로 구분된 차원을 축(axis)라고 함
    * like 그래프의 x축, y축

In [ ]:
a = np.array(range(5))
print(a)  # 1차원 배열
a[0], a[2], a[-1], a[len(a)]

[0 1 2 3 4]


(0, 2, 4)

In [ ]:
# b[0][0]  # 첫번째 행의 첫번째 열
b[0, 0]

0

In [ ]:
# 첫번째 행의 두번째 열
b[0, 1]

1

In [ ]:
# 마지막 행의 마지막 열
b[-1, -1]

5

## 배열 슬라이싱
* 다차원 배열의 원소 중 2개 이상의 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용

In [ ]:
a = np.array([range(4), range(4, 8)])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
# a[0] -> 첫 번째 행의 전체 열
a[0], a[0,:]

(array([0, 1, 2, 3]), array([0, 1, 2, 3]))

In [ ]:
# 두 번째 '열'의 모든 행. (모든 행의 두 번째 열)
a[:, 1]

array([1, 5])

In [ ]:
# 두 번째 행의, 두 번째 열부터 끝까지?
a[1, 1:]

array([5, 6, 7])

In [ ]:
# 첫번째 행에서 두번째 행까지, 첫번째 열에서 두번째 열까지.
a[:2, :2]  # a[0:2, 0:2]

array([[0, 1],
       [4, 5]])

## 💡 연습문제 2

In [61]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [72]:
#@markdown (1) 값 7을 인덱싱
print(m[1,2])

7


In [74]:
#@markdown (2) 값 14을 인덱싱
print(m[2,4])

14


In [76]:
#@markdown (3) 배열 [6,7]을 슬라이싱
print(m[1,1:3])

[6 7]


In [78]:
#@markdown (4) 배열 [7,12]을 슬라이싱
print(m[1:3,2])

[ 7 12]


In [80]:
#@markdown (5) 배열 [[3,4],[8,9]]을 슬라이싱
print(m[0:2,3:5])

[[3 4]
 [8 9]]


## 배열 인덱싱
* 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 `ndarray` 배열을 받을 수 있음 (인덱스 배열)
* 일종의 조건 검색 기능

### 불리언 (Boolean) 배열 인덱싱
* 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 함

In [ ]:
# 0~8 사이의 (끝포함) 짝수만 가진 배열
a1 = np.array(range(0, 9, 2))
# a2 = np.array([i for i in range(0, 9) if i % 2 == 0])
a2 = np.array([i for i in range(0, 9) if not i % 2])
a3 = np.array(range(9))[::2]  # 배열 슬라이싱도 증가폭이 된다
a1, a2, a3

(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]))

In [ ]:
# 짝수인 원소만 골라내고 싶다면?
# 짝수에 대응하는 곳에 True, 홀수에 대응하는 곳에 False
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# idx = np.array([True, False, True, False, True, False, True, False, True, False])
idx = np.array([i % 2 == 0 for i in range(10)])
idx

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[idx]  # 내가 보기를 원하는 곳만 True를 넣어놓은 배열을 [] 안에 넣으니까...
# 필터링

array([0, 2, 4, 6, 8])

In [ ]:
# 조건문 연산
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
a % 2 == 0  # 불리언 인덱스 배열 <- 비교 연산

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [ ]:
a[a % 3 == 0], a[a % 3 != 0], a[a // 2 == 1]

(array([0, 3, 6, 9]), array([1, 2, 4, 5, 7, 8]), array([2, 3]))

### 정수 배열 인덱싱
* 인덱스 배열의 원소 각각이 원래 `ndarray` 객체 원소 하나를 가리키는 인덱스 정수이여야 함

In [ ]:
a = np.array(range(1, 10)) * 11
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
# 0, 2, 4, 6, 8 -> 인덱스
idx = np.array([0, 2, 4, 6, 8])
a[idx], a[[0, 2, 4, 6, 8]]

(array([11, 33, 55, 77, 99]), array([11, 33, 55, 77, 99]))

* 이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없음
* 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 함

In [ ]:
idx = np.array([0] * 6 + [1] * 5 + [2] * 5)
print(idx)
a[idx]  # 해당 인덱스가 반복해서 등장하는 만큼.

[0 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

### 다차원 배열에서의 배열 인덱싱

In [ ]:
a = np.array([range(1,5), range(5,9), range(9,13)])
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 2,
 (3, 4))

In [ ]:
print(a[:,[0,3]])
# print(a[:,[3,0]])
print(a[:,[0,-1]])
print(a[:,[True, False, True, False]])
print(a[:,[i % 2 == 0 for i in range(4)]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [ ]:
a[[2, 0, 1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

## 💡 연습문제 3

In [4]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
# (1) 3의 배수 찾기
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
# (2) 4로 나누면 1이 남는 수 찾기
x[]

array([ 1,  5,  9, 13, 17])

In [ ]:
# (3) 3로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기


array([9])