<a href="https://colab.research.google.com/github/Felicette1963/Python_Numpy_Colab/blob/main/20230620_Python_Basic_Numpy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 배열의 연산

## 벡터화 연산 (vectorized operation)
* 명시적으로 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복 연산을 할 수 있음
* 선형 대수 공식과 동일한 아주 간단한 파이썬 코드를 작성할 수 있음

<br>
$$
x = \begin{bmatrix}1\\2\\3\\⋯\\10000\end{bmatrix},\quad
y = \begin{bmatrix}10001\\10002\\10003\\⋯\\20000\end{bmatrix}
$$

<br>
$$
z = x + y
$$

<br>
$$
\begin{bmatrix}1\\2\\3\\⋯\\10000\end{bmatrix}
+ \begin{bmatrix}10001\\10002\\10003\\⋯\\20000\end{bmatrix}
= \begin{bmatrix}1+10001\\2+10002\\3+10003\\⋯\\10000+20000\end{bmatrix}
= \begin{bmatrix}10002\\10004\\10006\\⋯\\30000\end{bmatrix}
$$



In [14]:
import numpy as np

In [15]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)
x, y

(array([    1,     2,     3, ...,  9998,  9999, 10000]),
 array([10001, 10002, 10003, ..., 19998, 19999, 20000]))

In [16]:
%%time
z = np.zeros_like(x)  # 2개의 배열을 더했을 때의 결과를 담아줄 새로운 배열
for i in range(len(z)):
    # range(len(z)) -> 해당 z 배열의 길이만큼을 가진 range => 반복했을 때 z의 길이만큼 반복해줄 수 있는 인덱스 range
    z[i] = x[i] + y[i]  # x와 y와 z의 길이가 일치하기 때문에 -> 반복을 하면 x, y의 모든 원소(요소) 인덱스로 찾아서
    # x + y 연산을 해주는 기능.

CPU times: user 7.31 ms, sys: 0 ns, total: 7.31 ms
Wall time: 11.8 ms


In [17]:
%%timeit
z = np.zeros_like(x)  # 2개의 배열을 더했을 때의 결과를 담아줄 새로운 배열
for i in range(len(z)):
    # range(len(z)) -> 해당 z 배열의 길이만큼을 가진 range => 반복했을 때 z의 길이만큼 반복해줄 수 있는 인덱스 range
    z[i] = x[i] + y[i]  # x와 y와 z의 길이가 일치하기 때문에 -> 반복을 하면 x, y의 모든 원소(요소) 인덱스로 찾아서
    # x + y 연산을 해주는 기능.

3.52 ms ± 63.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%%time
z = x + y

CPU times: user 66 µs, sys: 3 µs, total: 69 µs
Wall time: 88 µs


In [19]:
%%timeit
z = x + y

5.31 µs ± 153 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [20]:
z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [21]:
# 사칙 연산뿐 아니라 비교 연산과 같은 논리 연산도 벡터화 연산이 가능

In [22]:
x == y

array([False, False, False, ..., False, False, False])

In [23]:
(x == y) | (x < y)

array([ True,  True,  True, ...,  True,  True,  True])

In [24]:
# 배열의 각 원소를 일일히 비교하는 것이 아닌 배열의 모든 원소가 다 같은지 알고 싶다면 all 명령 사용
a = np.arange(1, 5)
b = np.array((4, 2, 2, 4))
c = np.arange(1, 5)
a, b, c

(array([1, 2, 3, 4]), array([4, 2, 2, 4]), array([1, 2, 3, 4]))

In [25]:
a == b

array([False,  True, False,  True])

In [26]:
np.all(a == b)  # 모두 일치 하냐

False

In [27]:
np.all(a == c)

True

In [28]:
np.any(a == c)

True

In [29]:
# 지수 함수, 로그 함수 등의 수학 함수도 벡터화 연산을 지원
a

array([1, 2, 3, 4])

In [30]:
np.exp(a)  # exponential (지수)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [31]:
10 ** a

array([   10,   100,  1000, 10000])

In [32]:
np.log(a+1)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터/행렬의 곱셈

In [33]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
x * 100  # [100, 100, 100, ...., 100]

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [35]:
x = np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
x * 100

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅
* 백터(또는 행렬)끼리 덧셈 혹은 뺄셈을 하려면 두 벡터(또는 행렬)의 크기가 같아야 함
* Numpy에선 서로 다른 크기를 가진 두 배열의 사칙 연산 지원 = 브로드캐스팅(broadcasting)
> 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞추는 방법

<br>
$$
x = \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix},\quad
x + 1 = \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix} + 1 = ?
$$
<br>
$$
\begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix} + 1
= \begin{bmatrix}0\\1\\2\\3\\4\end{bmatrix}
+ \begin{bmatrix}1\\1\\1\\1\\1\end{bmatrix}
= \begin{bmatrix}1\\2\\3\\4\\5\end{bmatrix}
$$

In [55]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [56]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [57]:
x + y

array([1, 2, 3, 4, 5])

In [58]:
x + 1

array([1, 2, 3, 4, 5])

In [59]:
np.full(5, 2)

array([2, 2, 2, 2, 2])

In [60]:
z = np.full_like(x, 2)
z

array([2, 2, 2, 2, 2])

In [61]:
x + z, x + 2

(array([2, 3, 4, 5, 6]), array([2, 3, 4, 5, 6]))

In [62]:
# 2차원 이상에서도 적용됨
# x = np.vstack([range(7)[i:i+3] for i in range(5)])
r = [range(7)[i:i+3] for i in range(5)]
print(r)
x = np.vstack(r)  # 열 기준으로 -> 행을 늘리면서 합쳐주는 거죠.
x, x.shape, x.ndim

[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]


(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]),
 (5, 3),
 2)

In [63]:
y = np.arange(5)
y, y.ndim

(array([0, 1, 2, 3, 4]), 1)

In [64]:
y2 = y[:, np.newaxis]
y2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [65]:
y3 = np.tile(y2, 3)
y3, y3.shape

(array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]]),
 (5, 3))

In [66]:
x + y3

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [67]:
x + y2

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [68]:
z = np.arange(3)
z

array([0, 1, 2])

In [69]:
x + z

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

## 차원 축소 연산 (dimension reduction)
> 행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 각 행에 처리된 연산으로 한 차원 낮은 벡터를 구성하게 하는 연산
* 최대/최소 : `min`, `max`, `argmin`, `argmax`
* 통계 : `sum`, `mean`, `median`, `std`, `var`
* 불리언 : `all`, `any`

In [73]:
x = np.arange(1,5)
x

array([1, 2, 3, 4])

In [74]:
np.sum(x), x.sum()

(10, 10)

In [75]:
x.min(), x.max()

(1, 4)

In [76]:
x.argmax() # 최대값의 위치

3

In [77]:
x.argmin() # 최소값의 위치

0

In [80]:
import random

arr = np.array(random.choices(range(1000_000), k = 5))
arr

array([361261, 580408, 273493, 427734,  31387])

In [82]:
arr.max(), arr.min()

(580408, 31387)

In [84]:
arr2 = ['민수','민철','철민','수민','철철']
arr2[arr.argmax()], arr2[arr.argmin()]

('민철', '철철')

In [85]:
arr

array([361261, 580408, 273493, 427734,  31387])

In [86]:
arr.mean(), np.mean(arr), arr.sum() / len(arr)

(334856.6, 334856.6, 334856.6)

In [87]:
# 대표값 -> 평균값, 최빈값, 중앙값(중간값)
np.median(arr)

361261.0

In [88]:
arr2 = np.array(random.choices(range(1000_000), k=6))
arr2

array([859457, 606353,  75391, 224109, 137564, 611920])

In [89]:
np.median(arr2)  #  짝수 개의 경우에는 중간에 있는 2값의 평균값.

415231.0

In [90]:
np.any(arr > 1_000_000)

False

In [91]:
np.all(arr > 0)

True

In [92]:
(arr > 0).all()  # 배열들 중에 모두가 True인가?

True

In [93]:
(arr > 500000).any()  # 배열들 중에 하나라도 True가 있는가?

True

* 연산의 대상이 2차원 이상인 경우에는 어느 차원으로 계산을 할 지를 axis 인수를 사용하여 지시
* axis=0인 경우는 열 연산, axis=1인 경우는 행 연산. 디폴트 값은 axis=0.
* axis 인수는 대부분의 차원 축소 명령에 적용할 수 있음

In [94]:
x = np.array(np.array(random.choices(range(1000_000), k=6))).reshape(2, -1)
x

array([[528067, 453374, 276445],
       [434299,  23775, 230249]])

In [95]:
x.sum()  # 차원 고려 안하고 모두를 더해버림

1946209

In [96]:
x.sum(axis=0)  # 열 합계 (열들 간의 연산)
# 다른 행의 같은 열들 간의 연산 -> 열의 수가 보존. (행이 축소)

array([962366, 477149, 506694])

In [97]:
x.sum(axis=1)  # 행 합계 (행들 간의 연산)
# 다른 열의 같은 행들 간의 연산 -> 행의 수가 보존. (열이 축소)
# axis => 축소할 축을 지정.

array([1257886,  688323])

## 💡 연습문제 5
실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값 도출
1. 전체의 최댓값
2. 각 행의 합
3. 각 행의 최댓값
4. 각 열의 평균
5. 각 열의 최솟값

In [121]:
number = np.array(range(0,30), dtype='f').reshape(-1, 6)
number

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]], dtype=float32)

In [122]:
# 전체의 최댓값
number.max()

29.0

In [123]:
# 각 행의 합
number.sum(axis=1)

array([ 15.,  51.,  87., 123., 159.], dtype=float32)

In [124]:
# 각 행의 최댓값
number.max(axis=1)

array([ 5., 11., 17., 23., 29.], dtype=float32)

In [128]:
# 각 열의 평균
number.mean(axis=0)

array([12., 13., 14., 15., 16., 17.], dtype=float32)

In [129]:
# 각 열의 최솟값
number.min(axis=0)

array([0., 1., 2., 3., 4., 5.], dtype=float32)

## 정렬
* `sort` : 배열 안의 원소를 크기에 따라 정렬하여 새로운 배열 생성
* 2차원 이상인 경우에는 행이나 열을 각각 따로따로 정렬
    * `axis=0` : 각각의 행을 따로따로 정렬
    * `axis=1` : 각각의 열을 따로따로 정렬
    * `axis=-1` : 가장 안쪽(나중)의 차원 (default)

In [98]:
a = np.array(
    (
    [4, 3, 5, 7],
    [1, 12, 11, 9],
    [2, 15, 1, 14]
    )
)
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [99]:
np.sort(a), np.sort(a, axis=-1), np.sort(a, axis=1) # axis=-1 (가장 안쪽), axis=1 열들 간의 정렬

(array([[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]]),
 array([[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]]),
 array([[ 3,  4,  5,  7],
        [ 1,  9, 11, 12],
        [ 1,  2, 14, 15]]))

In [100]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [102]:
np.sort(a)[:,::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [103]:
np.sort(a, axis=0), np.sort(a, axis=0)[::-1,:]

(array([[ 1,  3,  1,  7],
        [ 2, 12,  5,  9],
        [ 4, 15, 11, 14]]),
 array([[ 4, 15, 11, 14],
        [ 2, 12,  5,  9],
        [ 1,  3,  1,  7]]))

In [104]:
np.sort(a, axis=0), a  # 복사.

(array([[ 1,  3,  1,  7],
        [ 2, 12,  5,  9],
        [ 4, 15, 11, 14]]),
 array([[ 4,  3,  5,  7],
        [ 1, 12, 11,  9],
        [ 2, 15,  1, 14]]))

In [105]:
# sort 메서드는 해당 객체의 자료 자체가 변화하므로 주의
# 자체변화(in-place) 메서드 = 원본이 수정됨
print(a)
a.sort()
print(a)
a.sort(axis=0)
print(a)
a.sort(axis=1)
print(a)

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]
[[ 3  4  5  7]
 [ 1  9 11 12]
 [ 1  2 14 15]]
[[ 1  2  5  7]
 [ 1  4 11 12]
 [ 3  9 14 15]]
[[ 1  2  5  7]
 [ 1  4 11 12]
 [ 3  9 14 15]]


* `argsort` : 자료 정렬이 아니라 순서만 알고 싶다면 사용

In [106]:
a = np.array([42, 38, 12, 25])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [107]:
a[j]

array([12, 25, 38, 42])

In [108]:
np.sort(a)

array([12, 25, 38, 42])

In [110]:
a[j[::-1]]

array([42, 38, 25, 12])

## 💡 연습문제 6
> 두 번째 행을 기준으로 각 열(column)을 재정렬
```
array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
```

In [142]:
x = np.array([
    [1, 2, 3, 4],
    [46, 99, 100, 71],
    [81, 59, 90, 100]
])
x

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [143]:
np.argsort(x[1])

array([0, 3, 1, 2])

In [144]:
x[:, np.argsort(x[1])]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])