<a href="https://colab.research.google.com/github/Felicette1963/Python_Numpy_Colab/blob/main/20230620_Python_Basic_Numpy_04ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기술 통계

## 기술 통계(descriptive statistics)
> 데이터 집합에 대해 통계를 계산
* 데이터의 개수(count)
* 평균(mean, average)
* 분산(variance)
* 표준 편차(standard deviation)
* 최댓값(maximum)
* 최솟값(minimum)
* 중앙값(median)
* 사분위수(quartile)

In [32]:
import numpy as np

In [33]:
x = np.array([
    18, 5, 10, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8,
    2, 5, 4, 15, -1, 4, -7, -24, 7, 9, -6, 23, -13
])
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

## 데이터의 개수

In [34]:
len(x)

26

## 표본 평균
* 우리가 일반적으로 아는 평균
* 통계용어로는 표본 평균(sample average, sample mean)
<br>
$
\bar{x} = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{x_i}
$
(𝑁은 데이터의 개수)

In [35]:
np.mean(x), x.mean()

(4.8076923076923075, 4.8076923076923075)

## 표본 분산
* 표본 분산(sample variance) : 데이터와 표본 평균간의 거리의 제곱의 평균
* 표본 분산이 작으면 데이터가 모여있는 것이고 크면 흩어져 있는 것
<br>
$
s^2 = \frac{1}{N}\displaystyle\sum_{i=1}^{N}{(x_i-\bar{x})^2}
$

In [36]:
np.var(x), x.var()

(115.23224852071006, 115.23224852071006)

## 표본 표준편차
* 표본 표준편차(sample standard variance) : 표본 분산의 양의 제곱근 값
<br>
$
s = \sqrt{s^2}
$

In [37]:
np.std(x), x.std()

(10.734628476137871, 10.734628476137871)

## 최댓값과 최솟값

In [38]:
# 최댓값 (maximum) / 최솟값 (minimum)
np.max(x), x.max(), np.min(x), x.min()

(23, 23, -24, -24)

## 중앙값
* 중앙값(median) : 데이터를 크기대로 정렬하였을 때 가장 가운데에 있는 수
* 만약 데이터의 수가 짝수이면 가장 가운데에 있는 두 수의 평균을 사용


In [39]:
np.median(x)  # 내장 메소드 X.

5.0

## 사분위수
* 사분위수(quartile) : 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수
* 각각 1사분위수, 2사분위수, 3사분위수라고 함
* 1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%
* 따라서 2사분위수는 중앙값과 같음
* 때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 함
* 1사분위수는 25% 백분위수와 같음


In [40]:
np.percentile(x, 0)  # 최솟값. min

-24.0

In [41]:
np.percentile(x, 25)  # 25% 백분위수, 1사분위수

0.0

In [42]:
np.percentile(x, 50)  # 50% 백분위수, 2사분위수, 중앙값

5.0

In [43]:
np.percentile(x, 75)  # 75% 백분위수, 3사분위수

10.0

In [44]:
np.percentile(x, 100)  # 100% 백분위수, 4사분위수, 최댓값

23.0

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [45]:
np.random.seed(0)  # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [46]:
np.random.rand(5)  # rand(n) : n개의 길이를 가지는 배열에 각각 0~1 사이의 난수를 채워줌

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [47]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.random.shuffle(x)  # x를 섞어줌 -> x 자체를 섞어버림
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [50]:
np.random.choice(5, 5, replace=False)  # 5개 중에 5개를 선택 -> 비복원 -> shuffle

array([0, 4, 2, 1, 3])

In [51]:
np.random.choice(5, 3, replace=False)  # 5개 중에 3개를 선택 -> 비복원

array([4, 2, 3])

In [52]:
# np.random.choice(5, 10) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)
np.random.choice(5, 10, replace=True) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([0, 2, 4, 3, 3, 2, 4, 2, 0, 0])

In [53]:
# [0, 1, 2, 3, 4]
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([2, 2, 2, 2, 3, 3, 3, 3, 0, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [54]:
np.random.rand(10)

array([0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067,
       0.32504723, 0.03842543, 0.63427406, 0.95894927, 0.65279032])

In [55]:
np.random.rand(3, 5)

array([[0.63505887, 0.99529957, 0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548],
       [0.94957105, 0.66252687, 0.01357164, 0.6228461 , 0.67365963]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

array([[-0.22403878, -0.42018339,  0.99982969,  0.43103415, -0.65091287],
       [-1.49874039, -1.23063497,  0.19400719, -0.99838235, -0.3676376 ],
       [ 1.73719932,  0.59361275, -0.54236358, -1.71967238, -0.57890879]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

array([2, 8, 4, 3, 0, 4, 3, 6, 9, 8])

array([10, 18, 15, 19, 10, 19, 16, 15, 13, 11])

array([[18, 10, 14, 19, 16],
       [15, 17, 18, 18, 19],
       [12, 18, 16, 16, 19]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [ ]:
# 1.


array(['TAIL', 'TAIL', 'HEAD', 'HEAD', 'HEAD', 'HEAD', 'TAIL', 'TAIL',
       'TAIL', 'HEAD'], dtype='<U4')

In [ ]:
# 2.


3.66

In [ ]:
# 3.


array([-0.00317543, -0.01632423, -0.00067134,  0.01489356,  0.00521304,
        0.00611927, -0.01341497,  0.00476898,  0.0014845 ,  0.00529045,
        0.00422629, -0.01359781, -0.00041401, -0.00757871, -0.00050084,
       -0.00897401,  0.0131247 , -0.00858972, -0.00898942,  0.00074586,
       -0.01077099, -0.00424663, -0.00829965,  0.01411172,  0.00785804,
       -0.0005747 , -0.00391217,  0.00940918,  0.00405204,  0.00498052,
       -0.00026192, -0.0168823 , -0.00112466, -0.0053249 ,  0.00645055,
        0.01011842, -0.00657951,  0.00468385,  0.01735879, -0.00667713,
        0.01681922, -0.00852586,  0.0002296 , -0.00011146,  0.00011499,
       -0.00837678, -0.00591183, -0.0066772 ,  0.00326963,  0.00330035,
        0.02225944,  0.01370989, -0.00509843,  0.0032487 ,  0.00997118,
        0.00030602, -0.00069642,  0.00051575,  0.00867277, -0.00848321,
       -0.00325669,  0.00470433,  0.00311447,  0.00239583, -0.00369801,
        0.00972536,  0.02133868,  0.00406415, -0.00193177,  0.00

array([ 9968.24569061,  9805.52172515,  9798.93887103,  9944.87995133,
        9996.72298327, 10057.89564959,  9922.96930879,  9970.29178757,
        9985.09264399, 10037.91830117, 10080.34141693,  9943.27087728,
        9939.15428244,  9863.82832836,  9858.88811928,  9770.41436592,
        9898.64815922,  9813.6215047 ,  9725.40272392,  9732.65655233,
        9627.82619918,  9586.94035449,  9507.37214356,  9641.53752326,
        9717.30109408,  9711.71660794,  9673.72271651,  9764.74447753,
        9804.31162059,  9853.14223038,  9850.56147198,  9684.2613353 ,
        9673.36983564,  9621.86011642,  9683.9264325 ,  9781.91250933,
        9717.55231377,  9763.06789394,  9932.54293905,  9866.22208637,
       10032.16422056,  9946.63140825,  9948.91513051,  9947.80626305,
        9948.95015133,  9865.60998051,  9807.28616123,  9741.80092199,
        9773.65296712,  9805.90945388, 10024.18353955, 10161.61399384,
       10109.8056916 , 10142.64937851, 10243.78355919, 10246.91834384,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


array([ 2, 11, 34])

array(['a', 'b', 'c'], dtype='<U1')

array([2, 2, 1])

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

array([0, 2, 3, 1, 0, 0])

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [ ]:
np.random.seed(0)  # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [ ]:
np.random.rand(5)  # rand(n) : n개의 길이를 가지는 배열에 각각 0~1 사이의 난수를 채워줌

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)  # x를 섞어줌 -> x 자체를 섞어버림
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [ ]:
np.random.choice(5, 5, replace=False)  # 5개 중에 5개를 선택 -> 비복원 -> shuffle

array([0, 4, 2, 1, 3])

In [ ]:
np.random.choice(5, 3, replace=False)  # 5개 중에 3개를 선택 -> 비복원

array([4, 2, 3])

In [ ]:
# np.random.choice(5, 10) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)
np.random.choice(5, 10, replace=True) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([0, 2, 4, 3, 3, 2, 4, 2, 0, 0])

In [ ]:
# [0, 1, 2, 3, 4]
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([2, 2, 2, 2, 3, 3, 3, 3, 0, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [ ]:
np.random.rand(10)

array([0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067,
       0.32504723, 0.03842543, 0.63427406, 0.95894927, 0.65279032])

In [ ]:
np.random.rand(3, 5)

array([[0.63505887, 0.99529957, 0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548],
       [0.94957105, 0.66252687, 0.01357164, 0.6228461 , 0.67365963]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

array([-0.04411241, -0.36326702, -0.01234481,  0.04212149,  1.95929589,
       -0.1984257 ,  0.33053441, -1.43582841,  0.02752832,  1.12060466])

array([[-0.22403878, -0.42018339,  0.99982969,  0.43103415, -0.65091287],
       [-1.49874039, -1.23063497,  0.19400719, -0.99838235, -0.3676376 ],
       [ 1.73719932,  0.59361275, -0.54236358, -1.71967238, -0.57890879]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

array([2, 8, 4, 3, 0, 4, 3, 6, 9, 8])

array([10, 18, 15, 19, 10, 19, 16, 15, 13, 11])

array([[18, 10, 14, 19, 16],
       [15, 17, 18, 18, 19],
       [12, 18, 16, 16, 19]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [ ]:
# 1.


array(['TAIL', 'TAIL', 'HEAD', 'HEAD', 'HEAD', 'HEAD', 'TAIL', 'TAIL',
       'TAIL', 'HEAD'], dtype='<U4')

In [ ]:
# 2.


3.66

In [ ]:
# 3.


array([-0.00317543, -0.01632423, -0.00067134,  0.01489356,  0.00521304,
        0.00611927, -0.01341497,  0.00476898,  0.0014845 ,  0.00529045,
        0.00422629, -0.01359781, -0.00041401, -0.00757871, -0.00050084,
       -0.00897401,  0.0131247 , -0.00858972, -0.00898942,  0.00074586,
       -0.01077099, -0.00424663, -0.00829965,  0.01411172,  0.00785804,
       -0.0005747 , -0.00391217,  0.00940918,  0.00405204,  0.00498052,
       -0.00026192, -0.0168823 , -0.00112466, -0.0053249 ,  0.00645055,
        0.01011842, -0.00657951,  0.00468385,  0.01735879, -0.00667713,
        0.01681922, -0.00852586,  0.0002296 , -0.00011146,  0.00011499,
       -0.00837678, -0.00591183, -0.0066772 ,  0.00326963,  0.00330035,
        0.02225944,  0.01370989, -0.00509843,  0.0032487 ,  0.00997118,
        0.00030602, -0.00069642,  0.00051575,  0.00867277, -0.00848321,
       -0.00325669,  0.00470433,  0.00311447,  0.00239583, -0.00369801,
        0.00972536,  0.02133868,  0.00406415, -0.00193177,  0.00

array([ 9968.24569061,  9805.52172515,  9798.93887103,  9944.87995133,
        9996.72298327, 10057.89564959,  9922.96930879,  9970.29178757,
        9985.09264399, 10037.91830117, 10080.34141693,  9943.27087728,
        9939.15428244,  9863.82832836,  9858.88811928,  9770.41436592,
        9898.64815922,  9813.6215047 ,  9725.40272392,  9732.65655233,
        9627.82619918,  9586.94035449,  9507.37214356,  9641.53752326,
        9717.30109408,  9711.71660794,  9673.72271651,  9764.74447753,
        9804.31162059,  9853.14223038,  9850.56147198,  9684.2613353 ,
        9673.36983564,  9621.86011642,  9683.9264325 ,  9781.91250933,
        9717.55231377,  9763.06789394,  9932.54293905,  9866.22208637,
       10032.16422056,  9946.63140825,  9948.91513051,  9947.80626305,
        9948.95015133,  9865.60998051,  9807.28616123,  9741.80092199,
        9773.65296712,  9805.90945388, 10024.18353955, 10161.61399384,
       10109.8056916 , 10142.64937851, 10243.78355919, 10246.91834384,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


array([ 2, 11, 34])

array(['a', 'b', 'c'], dtype='<U1')

array([2, 2, 1])

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

array([0, 2, 3, 1, 0, 0])

# 난수 발생과 카운팅

## 시드 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 의미의 무작위 수가 아님
* 어떤 특정한 시작 숫자를 정해 주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성. 이런 시작 숫자를 시드(seed)라고 함
* 일단 생성된 난수는 다음번 난수 생성을 위한 시드값이 됨. 따라서 시드값은 한 번만 정해주면 됨.
* 시드는 보통 현재 시각 등을 이용하여 자동으로 정해지지만 사람이 수동으로 설정할 수도 있음 * 특정한 시드값이 사용되면 그 다음에 만들어지는 난수들은 모두 예측할 수 있음
* 고정된 결과를 얻기 위해서 실습엔 시드를 설정

In [ ]:
np.random.seed(0)  # 시드값 고정

### `rand` : 0과 1 사이의 난수를 발생

In [ ]:
np.random.rand(5)  # rand(n) : n개의 길이를 가지는 배열에 각각 0~1 사이의 난수를 채워줌

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

## 데이터의 순서 변경

### `shuffle`
* 데이터의 순서를 변경
* 자체 변환(in-place) 함수 (원본에 영향)

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(x)  # x를 섞어줌 -> x 자체를 섞어버림
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

## 데이터 샘플링
* 표본선택 혹은 샘플링(sampling) : 이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것

### `choice` : 샘플링에 사용
```
numpy.random.choice(a, size=None, replace=True, p=None)
```
* a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성
* size : 정수. 샘플 숫자
* replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능 (복원/비복원 추출)
* p : 배열. 각 데이터가 선택될 수 있는 확률

In [ ]:
np.random.choice(5, 5, replace=False)  # 5개 중에 5개를 선택 -> 비복원 -> shuffle

array([0, 4, 2, 1, 3])

In [ ]:
np.random.choice(5, 3, replace=False)  # 5개 중에 3개를 선택 -> 비복원

array([4, 2, 3])

In [ ]:
# np.random.choice(5, 10) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)
np.random.choice(5, 10, replace=True) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([0, 2, 4, 3, 3, 2, 4, 2, 0, 0])

In [ ]:
# [0, 1, 2, 3, 4]
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]) # 복원, 5개 중에 10개를 선택 (뽑았던 것을 또 뽑는다)

array([2, 2, 2, 2, 3, 3, 3, 3, 0, 3])

## 난수 생성
* `rand` : 0부터 1 사이의 균일 분포
* `randn` : 표준 정규 분포
* `randint` : 균일 분포의 정수 난수

### `rand` : 0부터 1 사이에서 균일한 확률 분포로 실수 난수를 생성
* 숫자 인수는 생성할 난수의 크기
* 여러 개의 인수를 넣으면 해당 크기를 가진 행렬을 생성

In [ ]:
np.random.rand(10)

array([0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067,
       0.32504723, 0.03842543, 0.63427406, 0.95894927, 0.65279032])

In [ ]:
np.random.rand(3, 5)

array([[0.63505887, 0.99529957, 0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232, 0.31720174, 0.77834548],
       [0.94957105, 0.66252687, 0.01357164, 0.6228461 , 0.67365963]])

### `randn` : 기댓값이 0이고 표준편차가 1인 표준 정규 분포(standard normal distribution)를 따르는 난수를 생성

In [ ]:
np.random.randn(10)

array([-0.68658948,  0.01487332, -0.3756659 , -0.03822364,  0.36797447,
       -0.0447237 , -0.30237513, -2.2244036 ,  0.72400636,  0.35900276])

In [ ]:
np.random.randn(3, 5)

array([[ 1.07612104,  0.19214083,  0.85292596,  0.01835718,  0.42830357],
       [ 0.99627783, -0.49114966,  0.71267817,  1.11334035, -2.15367459],
       [-0.41611148, -1.07089699,  0.22113881, -1.12305712, -1.05075796]])

### `randint`
```
numpy.random.randint(low, high=None, size=None)
```
만약 `high`를 입력하지 않으면 0과 `low`사이의 숫자, `high`를 입력하면 `low`와 `high`는 사이의 숫자를 출력. `size`는 난수의 숫자

In [ ]:
np.random.randint(10)  # 최대값 -> 그것보다 작은 범위에서의 랜덤 숫자 (끝점 제외)
# np.random.randint(10, size=1)  # 최대값 -> 그것보다 작은 범위에서의 랜덤 숫자

8

In [ ]:
np.random.randint(10, size=10)  # 시작점

array([8, 3, 8, 2, 8, 4, 3, 0, 4, 3])

In [ ]:
np.random.randint(10, 20, size=10)  # 시작점, 끝점

array([16, 19, 18, 10, 18, 15, 19, 10, 19, 16])

In [ ]:
np.random.randint(10, 20, size=(3,5))

array([[15, 13, 11, 18, 10],
       [14, 19, 16, 15, 17],
       [18, 18, 19, 12, 18]])

## 💡 연습문제 7
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 작성하라
2. 주사위를 100번 던져서 나오는 숫자의 평균
3. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [ ]:
# 1.
np.random.choice([0, 1], size=10, replace=True)

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [ ]:
np.random.choice(["H", "T"], size=10, replace=True)

array(['H', 'T', 'H', 'H', 'T', 'T', 'T', 'T', 'H', 'T'], dtype='<U1')

In [ ]:
# 2.
# np.random.randint(1, 7, 100)
# np.random.randint(1, 7, 100).mean()
np.random.choice(range(1,7), size=100, replace=True).mean()

3.52

In [58]:
# 3.
random_list = np.random.randn(250) / 100
random_list

array([-2.99272356e-03,  7.08507685e-03, -5.79825126e-03,  1.68992749e-02,
       -4.26598366e-03, -1.96926916e-03, -1.86805984e-02, -1.30729405e-02,
       -4.40559294e-03, -9.98825343e-03, -1.04856139e-02,  5.71891148e-03,
        1.50269100e-03,  7.88473865e-03,  2.10187965e-02, -6.51176939e-03,
        3.37360872e-03, -1.62458195e-02, -2.88568122e-03, -3.54680025e-03,
       -9.29567520e-03,  3.24580517e-04, -3.16484702e-03,  1.06605778e-02,
        4.63858828e-03, -1.44927076e-02,  6.34463855e-03,  1.43692767e-02,
       -1.21142064e-02,  2.90135499e-03, -1.60419962e-02,  1.01505813e-02,
        4.69662190e-03,  4.22646424e-03, -1.68823281e-02, -1.69480065e-02,
        1.29587702e-03,  2.54654707e-03, -7.38810865e-04, -4.66007661e-03,
        1.88017278e-02,  9.84231079e-03,  1.42654119e-02, -1.15284674e-02,
        1.45556787e-02,  3.80704705e-03, -2.05476681e-03,  8.59114575e-03,
       -1.07408218e-02,  7.40780083e-03,  1.52729651e-02,  2.17421704e-03,
        8.56927250e-03,  

In [60]:
start = 10000 # 시작값 만원
price = np.empty(250)
for i, v in enumerate(random_list):
  start *= (1 + v)  #변동 금액 전체 1 X 변동금액
  price[i] = start
price

array([ 9970.07276441, 10040.7114961 ,  9982.49292801, 10151.18982054,
       10107.88501061, 10087.97986443,  9899.53036387,  9770.11439262,
        9727.07124562,  9629.91479289,  9528.93922465,  9583.43438459,
        9597.83532522,  9673.51174839,  9876.83732311,  9812.5216362 ,
        9845.6252448 ,  9685.67499431,  9657.72522383,  9623.47120156,
        9534.01453894,  9537.10909431,  9506.92560301,  9608.27492329,
        9652.84375473,  9512.94791313,  9573.3041292 ,  9710.86558562,
        9593.22615588,  9621.05951051,  9466.71851021,  9562.81120588,
        9607.72411442,  9648.3308168 ,  9485.44453007,  9324.68515492,
        9336.7688001 ,  9360.54532134,  9353.62964875,  9310.04101799,
        9485.08587501,  9578.44103808,  9715.0814446 ,  9603.08144476,
        9742.86081276,  9779.95234225,  9759.85682076,  9843.70517323,
        9737.97568993,  9810.11267437,  9959.94218328,  9981.59725929,
       10067.13228619, 10163.20022078, 10021.20447452, 10013.37586638,
      

## 정수 데이터 카운팅
* 만약 난수가 정수값이면 unique 명령이나 bincount 명령으로 데이터 값을 분석

### `unique`
* unique 함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
* return_counts 인수를 True 로 설정하면 각 값을 가진 데이터 갯수도 출력


In [62]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [63]:
a = np.array(list('abbca'))
a

array(['a', 'b', 'b', 'c', 'a'], dtype='<U1')

In [64]:
np.unique(a, return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

In [65]:
index, value = np.unique(a, return_counts=True)
index, value

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1]))

In [66]:
# dict(np.unique(a, return_counts=True))

In [67]:
zip(np.unique(a, return_counts=True)) # 같은 값이 있는 것들이 튜플로 묶어준다.

In [69]:
list(zip(np.unique(a, return_counts=True)))

[(array(['a', 'b', 'c'], dtype='<U1'),), (array([2, 2, 1]),)]

In [68]:
dict(zip(*np.unique(a, return_counts=True)))

{'a': 2, 'b': 2, 'c': 1}

### `bincount`
* `unique` 함수는 데이터에 존재하는 값에 대해서만 갯수를 세므로 데이터 값이 나올 수 있음에도 불구하고 데이터가 하나도 없는 경우에는 정보를 주지 않음
* 따라서 데이터가 주사위를 던졌을 때 나오는 수처럼 특정 범위안의 수인 경우에는 `bincount` 함수에 `minlength` 인수를 설정하여 쓰는 것이 더 편리
* `bincount` 함수는 0 부터 `minlength` - 1 까지의 숫자에 대해 각각 카운트
* 데이터가 없을 경우에는 카운트 값이 0이 됨

In [70]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6) # 1 = 2, 2 = 3, 3 = 1

array([0, 2, 3, 1, 0, 0])